version: '3.9'
services:
  website:
    build: './packages/website'
    environment:
      - PORT=${SERVICE_WEBSITE_HOST_PORT}
    ports:
      - '${SERVICE_WEBSITE_CONTAINER_PORT}:${SERVICE_WEBSITE_HOST_PORT}'
  server:
    build: './packages/server'
    ports:
      - '${SERVICE_SERVER_PORT}:80'
  api:
    build: './packages/api'
    environment:
      - PORT=${SERVICE_API_HOST_PORT}
    ports:
      - ${SERVICE_API_CONTAINER_PORT}:${SERVICE_API_HOST_PORT}
  redocly:
    build: './packages/redocly'
    environment:
      - PORT=${SERVICE_REDOCLY_HOST_PORT}
      - OPENAPI_FILE_URL=${SERVICE_REDOCLY_ENVIRONMENT_OPENAPI_FILE_URL}
    ports:
      - '${SERVICE_REDOCLY_CONTAINER_PORT}:${SERVICE_REDOCLY_HOST_PORT}'
    depends_on:
      - 'api'
  stoplight:
    build: './packages/stoplight'
    environment:
      - PORT=${SERVICE_STOPLIGHT_HOST_PORT}
      - REACT_APP_OPENAPI_FILE_URL=${SERVICE_STOPLIGHT_ENVIRONMENT_REACT_APP_OPENAPI_FILE_URL}
    ports:
      - '${SERVICE_STOPLIGHT_CONTAINER_PORT}:${SERVICE_STOPLIGHT_HOST_PORT}'
